name: "Build"

on: 
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      dotnet_version:
        description: 'The version of .NET to use'
        required: false
        default: '8.0.x' # Latest dotnet version.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pwd before Checkout
        run: |
          echo "Current directory before checkout:"
          pwd
          ls -lah

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Pwd after Checkout
        run: |
          echo "Current directory after checkout:"
          pwd
          ls -lah

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ github.event.inputs.dotnet_version }}

      - name: Build dotnet project
        shell: pwsh
        run: |
          Write-Host "Starting build process." -ForegroundColor Green
          pwsh ./scripts/build.ps1
          Write-Host "Build process completed." -ForegroundColor Green

      - name: Pwd after Build
        shell: pwsh
        run: |
          Write-Host "Current directory after build:" -ForegroundColor Green
          Write-Host "$(pwd)" -ForegroundColor Green
          Write-Host "Files in directory:" -ForegroundColor Green
          Write-Host "$(ls -lah)" -ForegroundColor Green