name: "Build"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      dotnet_version:
        description: 'The version of .NET to use'
        required: false
        default: '8.0.x' # Latest dotnet version.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - uses: ./.github/actions/build-action
        with:
          dotnet_version: "8.0.x"
          upload_artifacts_path: "ci"

  artifacts:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Pwd before Downloading Artifacts
        if: success()
        shell: pwsh
        run: |
          Write-Host "Current directory before downloading artifacts:" -ForegroundColor Green
          pwd
          Write-Host "Files in directory:" -ForegroundColor Green
          ls -lah

      - name: Download build artifacts.
        uses: actions/download-artifact@v4
        with:
          name: build-results
          path: ./ci

      - name: Pwd after Downloading Artifacts
        if: success()
        shell: pwsh
        run: |
          Write-Host "Current directory after downloading artifacts:" -ForegroundColor Green
          pwd
          Write-Host "Files in directory:" -ForegroundColor Green
          ls -lah